# Generated by Django 5.1.5 on 2025-01-20 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cook",
            options={"verbose_name": "Cook", "verbose_name_plural": "Cooks"},
        ),
        migrations.RemoveField(
            model_name="ingredient",
            name="dish",
        ),
        migrations.AddField(
            model_name="dish",
            name="dish",
            field=models.ManyToManyField(to="service.ingredient"),
        ),
        migrations.AlterField(
            model_name="cook",
            name="years_of_experience",
            field=models.IntegerField(default=0),
        ),
    ]
