# Generated by Django 5.1.5 on 2025-01-20 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "service",
            "0002_alter_cook_options_remove_ingredient_dish_dish_dish_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="dish",
            old_name="dish",
            new_name="ingredients",
        ),
    ]
