# Generated by Django 5.1.5 on 2025-01-30 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0003_rename_dish_dish_ingredients"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cook",
            options={
                "ordering": ["username"],
                "verbose_name": "Cook",
                "verbose_name_plural": "Cooks",
            },
        ),
        migrations.AlterModelOptions(
            name="dish",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="dishtype",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="ingredient",
            options={"ordering": ["name"]},
        ),
    ]
